"use client";
import { Sector } from "@/lib/types";
import { customers, products, sectorCopy } from "@/lib/data";
import { Sidebar } from "./sidebar";
import { Icon } from "./icons";

const euro = new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });
export function Dashboard({ sector, reset }: { sector: Sector; reset: () => void }) {
 const copy = sectorCopy[sector];
 return <div className="min-h-screen bg-ink lg:pl-64"><Sidebar/><main className="mx-auto max-w-[1500px] p-5 sm:p-8 lg:p-10">
  <header className="flex items-center justify-between"><div><p className="text-xs text-zinc-500">Lunes, 21 de septiembre</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Buenos días, Alex <span className="inline-block rotate-12">👋</span></h1></div><div className="flex items-center gap-2"><button className="rounded-lg border border-line p-2.5 text-zinc-400"><Icon name="search" className="h-4 w-4"/></button><button className="rounded-lg border border-line p-2.5 text-zinc-400"><Icon name="bell" className="h-4 w-4"/></button><button className="ml-2 flex items-center gap-2 rounded-lg bg-lime px-4 py-2.5 text-xs font-bold text-ink"><Icon name="plus" className="h-4 w-4"/>Crear producto</button></div></header>
  <section className="relative mt-8 overflow-hidden rounded-2xl border border-lime/20 bg-gradient-to-r from-[#151a12] to-panel p-6 sm:p-8"><div className="absolute -right-16 -top-28 h-72 w-72 rounded-full bg-lime/[.07] blur-3xl"/><p className="text-[10px] font-bold uppercase tracking-[.2em] text-lime">Tu espacio · {copy.label}</p><h2 className="mt-2 text-2xl font-semibold">{copy.title}</h2><p className="mt-2 text-sm text-zinc-400">{copy.subtitle}</p><button onClick={reset} className="mt-5 text-xs font-medium text-zinc-400 underline decoration-zinc-700 underline-offset-4">Cambiar sector</button></section>
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Ingresos totales","12.840 €","+18,2%"],["Ingresos recurrentes","3.246 €","+12,4%"],["Clientes activos","684","+8,1%"],["Conversión","4,8%","+0,6%"]].map(([label,value,change],i)=><article key={label} className="rounded-xl border border-line bg-panel p-5"><div className="flex items-center justify-between"><p className="text-xs text-zinc-500">{label}</p><span className="rounded-md bg-lime/10 px-2 py-1 text-[10px] font-medium text-lime">{change}</span></div><p className="mt-4 text-2xl font-semibold tracking-tight">{value}</p><div className="mt-5 flex h-7 items-end gap-1">{[32,55,42,70,52,78,66,90,73,100,82,96].map((h,j)=><span key={j} className={`flex-1 rounded-sm ${i===0?"bg-lime/60":"bg-zinc-700"}`} style={{height:`${h}%`}}/>)}</div></article>)}</section>
  <section className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><article className="overflow-hidden rounded-xl border border-line bg-panel"><div className="flex items-center justify-between p-5"><div><h3 className="text-sm font-semibold">Productos</h3><p className="mt-1 text-xs text-zinc-500">Rendimiento de tus productos activos</p></div><button className="flex items-center gap-1 text-xs text-zinc-400">Ver todos <Icon name="arrow" className="h-3 w-3"/></button></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-y border-line bg-white/[.018] text-[10px] uppercase tracking-wider text-zinc-600"><tr><th className="px-5 py-3 font-medium">Producto</th><th className="px-5 py-3 font-medium">Tipo</th><th className="px-5 py-3 font-medium">Precio</th><th className="px-5 py-3 font-medium">Ventas</th></tr></thead><tbody>{products.map((p,i)=><tr key={p.id} className={i<products.length-1?"border-b border-line":""}><td className="px-5 py-4"><span className="mr-3 inline-flex h-8 w-8 items-center justify-center rounded-lg bg-white/[.05] text-zinc-400">{i+1}</span><span className="font-medium">{p.name}</span></td><td className="px-5 py-4 text-zinc-500">{p.type}</td><td className="px-5 py-4">{euro.format(p.price)}</td><td className="px-5 py-4 text-zinc-400">{p.sales}</td></tr>)}</tbody></table></div></article>
  <article className="rounded-xl border border-line bg-panel p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">Actividad reciente</h3><p className="mt-1 text-xs text-zinc-500">Últimos clientes</p></div><button className="text-xs text-zinc-500">Ver todos</button></div><div className="mt-5 space-y-1">{customers.map((c,i)=><div key={c.id} className="flex items-center gap-3 rounded-lg py-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-white/[.05] text-[10px] font-semibold text-zinc-300">{c.name.split(" ").map(n=>n[0]).join("")}</span><div className="min-w-0"><p className="truncate text-xs font-medium">{c.name}</p><p className="mt-1 truncate text-[10px] text-zinc-600">{c.product}</p></div><div className="ml-auto text-right"><p className="text-xs font-medium text-lime">+{euro.format(c.spent)}</p><p className="mt-1 text-[10px] text-zinc-600">{c.joinedAt}</p></div></div>)}</div></article></section>
  <section className="mt-6 grid gap-4 sm:grid-cols-3"><article className="rounded-xl border border-line bg-panel p-5"><span className="text-xs text-zinc-500">Pagos procesados</span><p className="mt-2 text-lg font-semibold">Stripe Connect</p><span className="mt-4 inline-flex items-center gap-2 text-xs text-lime"><i className="h-1.5 w-1.5 rounded-full bg-lime"/>Cuenta preparada</span></article><article className="rounded-xl border border-line bg-panel p-5"><span className="text-xs text-zinc-500">Suscripciones activas</span><p className="mt-2 text-lg font-semibold">171 miembros</p><p className="mt-4 text-xs text-zinc-600">MRR de 3.246 €</p></article><article className="rounded-xl border border-dashed border-zinc-700 bg-panel/40 p-5"><span className="text-xs text-zinc-500">Próximamente</span><p className="mt-2 text-lg font-semibold">Telegram + Discord</p><p className="mt-4 text-xs text-zinc-600">Automatiza el acceso de tu comunidad</p></article></section>
 </main></div>
}
